name: ecommerce_test
description:
version: 1.0.0+1

environment:
  sdk: ^3.6.0-216.1.beta

dependencies:
  flutter:
    sdk: flutter
  intl: 0.19.0
  go_router: 14.1.1
  flutter_riverpod: 2.5.1
  riverpod_annotation: 2.3.5
  flutter_layout_grid: ^2.0.2
  flutter_launcher_icons: ^0.9.2
  sqflite: ^2.0.0+4
  path: ^1.8.0
  path_provider: 2.1.3
  dio: ^5.0.0
  connectivity_plus: ^2.3.0


  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf

  uses-material-design: true

flutter_icons:
   ios: true
   android: true
   remove_alpha_ios: true
   image_path_ios: "assets/app-icon.png"
   image_path_android: "assets/app-icon.png"
   adaptive_icon_background: "assets/app-icon-background.png"
   adaptive_icon_foreground: "assets/app-icon-foreground.png"


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:


  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
